server:
  port: 9007
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 10.211.55.7
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
weixin:
  # 应用ID
  appId: wx8397f8696b538317
  # 商户ID
  partner: 1473426802
  # 秘钥
  partnerKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  # 支付回调地址
  notifyUrl: http://127.0.0.1/weixin/pay/notify/url
# 配置支付交换机和队列
mq:
  pay:
    # 交换机
    exchange:
      order: exchange.order
      seckillorder: exchange.seckillorder
    # 对列名称
    queue:
      order: queue.order
      seckillorder: queue.seckillorder
    routing:
      key: queue.order
      seckillkey: queue.seckillorder