server:
  port: 9008
spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.7:3306/changgou_seckill
    username: root
    password: 123456
  rabbitmq:
    host: 10.211.55.7
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 10.211.55.7
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    dafault:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
          atrategy: SEMAPHORE
# 配置支付交换机和队列
mq:
  pay:
    # 交换机
    exchange:
      seckillorder: exchange.seckillorder
    # 对列名称
    queue:
      seckillorder: queue.seckillorder
    routing:
      seckillkey: queue.seckillorder