server:
  port: 9200
spring:
  application:
    name: user-oauth
  redis:
    host: 10.211.55.7
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.7:3306/changgou_oauth
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
oauth:
  #token存储到redis的过期时间
  ttl: 3600
  # 客户端id
  clientId: changgou
  # 客户端秘钥
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    # 指定整数路径
    location: classpath:/changgou.jks
    # 秘钥
    secret: changgou
    # 证书别名
    alias: changgou
    # 证书密码
    password: changgou