server:
  port: 9006
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.7:3306/changgou_order
    username: root
    password: 123456
  redis:
    host: 10.211.55.7
    port: 6379
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 10.211.55.7
    port: 5672
    username: guest
    password: guest
  # 微服务组名
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
# 配置支付交换机和队列
mq:
  pay:
    # 交换机
    exchange:
      order: exchange.order
    # 对列名称
    queue:
      order: queue.order
    routing:
      key: queue.order
